<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CustomMedication extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'ingredients', 'preparation_instructions',
        'dosage', 'frequency_id', 'duration', 'instructions',
        'base_price', 'created_by', 'is_active'
    ];
     protected $casts = [
        'base_price' => 'decimal:2',
        'is_active' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];


    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function frequency()
    {
        return $this->belongsTo(PharmacyFrequency::class);
    }

    public function orderItems()
    {
        return $this->hasMany(MedicationOrderItem::class);
    }
     public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope a query to only include inactive medications.
     */
    public function scopeInactive($query)
    {
        return $query->where('is_active', false);
    }

    /**
     * Scope a query to search medications.
     */
    public function scopeSearch($query, $search)
    {
        return $query->where('name', 'like', "%{$search}%")
                    ->orWhere('ingredients', 'like', "%{$search}%")
                    ->orWhere('dosage', 'like', "%{$search}%");
    }

    /**
     * Get the total number of times this medication has been ordered.
     */
    public function getTotalOrdersAttribute()
    {
        return $this->orderItems()->count();
    }

    /**
     * Get the total revenue generated by this medication.
     */
    public function getTotalRevenueAttribute()
    {
        return $this->orderItems()->sum('total_price');
    }

    /**
     * Activate the medication.
     */
    public function activate()
    {
        $this->update(['is_active' => true]);
        return $this;
    }

    /**
     * Deactivate the medication.
     */
    public function deactivate()
    {
        $this->update(['is_active' => false]);
        return $this;
    }
}
